create database GestionDistribucion;
use GestionDistribucion;
CREATE TABLE PROVINCIAS (
	COD varchar(2) primary key,
    PROVINCIA varchar(22) not null);
    
CREATE TABLE POBLACIONES (
	NUM int auto_increment primary key,
    POBLACION varchar(47) not null);
    
create TABLE CODIGOSPOSTALES (
	CODIGO_POSTAL VARCHAR(5),
    NUM INT,FOREIGN KEY (NUM) REFERENCES POBLACIONES(NUM),
    primary key (CODIGO_POSTAL,NUM));

CREATE TABLE CLIENTES (
	NUMERO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO INT(1) not null,
    NIF_CIF varchar(9) not null,
    NOMBRE varchar(20),
    APELLIDOS VARCHAR(20),
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONO_FIJO VARCHAR(9),
    TELEFONO_MOVIL VARCHAR(9),
    DIRECCION VARCHAR(40),
    COD_POST VARCHAR(5),
    POBLACION VARCHAR(47),
    PROVINCIA VARCHAR(22),
    CONTRASENA INT NOT NULL,
    NUM_CUENTA_CONTABLE INT,
    CONFIRMADO TINYINT(1),
    ENVIADO TINYINT(1));

CREATE TABLE FAMILIAS (
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL);
    
CREATE TABLE LOTES(
	NUM_LOTE INT AUTO_INCREMENT PRIMARY KEY,
    LOTE VARCHAR(15) NOT NULL,
    FECHA_CADUCIDAD DATE,
    ARTICULO INT(11), FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    STOCK INT);
    
CREATE TABLE ARTICULOS (
	COD INT AUTO_INCREMENT PRIMARY KEY,
    CODPRO VARCHAR(11),
    NOMBRE VARCHAR(50) NOT NULL,
    COSTE DECIMAL(5,2) NOT NULL,
    PRECIO_MAYORISTA DECIMAL(5,2) NOT NULL,
    PRECIO_MINORISTA DECIMAL(5,2) NOT NULL,
    IVA DECIMAL(3,2) ,
    UNIDADES_CAJA INT,
    STOCK_MINIMO INT NOT NULL,
    STOCK INT,
    FAMILIA INT,FOREIGN KEY (FAMILIA) REFERENCES FAMILIAS(NUM),
    RESERVADOS INT,
    PROVEEDOR INT NOT NULL, FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES(NUMERO));

CREATE TABLE FACTURAS_CLIENTE (
    NUM INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE INT REFERENCES CLIENTES (NUMERO),
    FECHA DATE,
    PAGADA BOOLEAN
);
    
CREATE TABLE FILAS_FACTURAS_CLIENTE (
	FACTURA INT NOT NULL, FOREIGN KEY (FACTURA) REFERENCES FACTURAS_CLIENTE(NUM),
    ARTICULO INT NOT NULL, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    LOTE INT, FOREIGN KEY (LOTE) REFERENCES LOTES(NUM_LOTE),
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(5,2),
    PRIMARY KEY (FACTURA,ARTICULO,LOTE));
       
CREATE TABLE ALBARAN_CLIENTE (
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE INT,FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(NUMERO),
    FECHA DATE,
    NUM_FACTURA INT, FOREIGN KEY (NUM_FACTURA) REFERENCES FACTURAS_CLIENTE(NUM),
    ACTUALIZADO_ALMACEN BOOLEAN,
    FACTURADO BOOLEAN);

CREATE TABLE FILAS_ALBARAN_CLIENTE (
	ALBARAN INT NOT NULL, FOREIGN KEY (ALBARAN) REFERENCES ALBARAN_CLIENTE(NUM),
    ARTICULO INT NOT NULL, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    LOTE INT, FOREIGN KEY (LOTE) REFERENCES LOTES(NUM_LOTE),
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(5,2),
    PRIMARY KEY (ALBARAN,ARTICULO,LOTE));
    
CREATE TABLE PEDIDOS_CLIENTE (
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE INT, FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(NUMERO),
    FECHA DATE,
    ENVIADO BOOLEAN,
    NUM_ALBARAN INT, FOREIGN KEY (NUM_ALBARAN) REFERENCES ALBARAN_CLIENTE(NUM));
    
CREATE TABLE FILAS_PEDIDOS_CLIENTE (
	PEDIDO INT NOT NULL, FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS_CLIENTE(NUM),
    ARTICULO INT NOT NULL, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(5,2),
    PRIMARY KEY (PEDIDO,ARTICULO));
    
CREATE TABLE PROVEEDORES (
	NUMERO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(40),
    COD_POST VARCHAR(5),
    POBLACION VARCHAR(47),
    PROVINCIA VARCHAR(22),
    NIF VARCHAR(9) NOT NULL,
    TELEFONO_FIJO VARCHAR(9),
    TELEFONO_MOVIL VARCHAR(9),
    EMAIL VARCHAR(30) NOT NULL,
    NUM_CUENTA_CONTABLE INT);

CREATE TABLE FACTURAS_PROVEEDOR(
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    PROVEEDOR INT, FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES(NUMERO),
    FECHA DATE,
    PAGADA BOOLEAN);
  
CREATE TABLE FILAS_FACTURAS_PROVEEDOR(
	FACTURA INT, FOREIGN KEY (FACTURA) REFERENCES FACTURAS_PROVEEDOR(NUM),
    ARTICULO INT, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    LOTE INT, FOREIGN KEY (LOTE) REFERENCES LOTES(NUM_LOTE),
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(5,2),
    CONSTRAINT CLAVE PRIMARY KEY (FACTURA,ARTICULO,LOTE)); 
    
CREATE TABLE ALBARANES_PROVEEDOR (
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    PROVEEDOR INT,FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES(NUMERO),
    FECHA DATE,
    NUM_FACTURA INT, FOREIGN KEY (NUM_FACTURA) REFERENCES FACTURAS_PROVEEDOR(NUM),
    ACTUALIZADO_ALMACEN BOOLEAN,
    FACTURADO BOOLEAN);
    
CREATE TABLE FILAS_ALBARAN_PROVEEDOR (
	ALBARAN INT NOT NULL, FOREIGN KEY (ALBARAN) REFERENCES ALBARANES_PROVEEDOR(NUM),
    ARTICULO INT NOT NULL, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    LOTE INT,FOREIGN KEY (LOTE) REFERENCES LOTES(NUM_LOTE),
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(5,2),
    CONSTRAINT CLAVE PRIMARY KEY (ALBARAN,ARTICULO,LOTE));
	
CREATE TABLE PEDIDOS_PROVEEDOR (
	NUM INT AUTO_INCREMENT PRIMARY KEY,
    PROVEEDOR INT, FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES(NUMERO),
    FECHA DATE,
    CONFIRMADO BOOLEAN,
    ENVIADO BOOLEAN,
    NUM_ALBARAN INT, FOREIGN KEY (NUM_ALBARAN) REFERENCES ALBARANES_PROVEEDOR(NUM));    
    
CREATE TABLE FILAS_PEDIDOS_PROVEEDOR (
	PEDIDO INT NOT NULL, FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS_PROVEEDOR(NUM),
    ARTICULO INT NOT NULL,FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    CANTIDAD INT NOT NULL,
    CONSTRAINT CLAVE PRIMARY KEY (PEDIDO,ARTICULO));
    
CREATE TABLE PRECIOS_CLIENTE (
	CLIENTE INT NOT NULL, FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(NUMERO),
    ARTICULO INT NOT NULL, FOREIGN KEY (ARTICULO) REFERENCES ARTICULOS(COD),
    PRECIO DECIMAL(5,2) NOT NULL,
    PRIMARY KEY(ARTICULO,CLIENTE));
    
CREATE TABLE DATOSEMPRESA (
	NIF varchar(9) NOT NULL,
	NOMBRE varchar(45) DEFAULT NULL,
	DIRECCION varchar(45) DEFAULT NULL,
	CODPOS varchar(5) DEFAULT NULL,
	POBLACION VARCHAR(47),
    PROVINCIA VARCHAR(22),
	FIJO varchar(9) DEFAULT NULL,
	MOVIL varchar(9) DEFAULT NULL,
	EMAIL varchar(30) DEFAULT NULL,
	PRIMARY KEY (NIF)
) 